name: Publish package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -z "${NODE_AUTH_TOKEN}" ]; then
            echo "NPM_TOKEN secret is not configured. Add an automation token (npm token create --read-only false --automation) as repository secret NPM_TOKEN." >&2
            exit 1
          fi
          TAG=${GITHUB_REF##*/}
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "v${PKG_VERSION}" != "${TAG}" ]; then
            echo "Tag ${TAG} does not match package.json version ${PKG_VERSION}. Aborting publish." >&2
            exit 1
          fi
          npm publish --access public